### ISSUE TITLE
grpc err

### ISSUE THREAD

**Issue by cx2c** [short-d/short#1005]
config:  GRPC_API_PORT=8081

[Short] [Error] 2020-08-26 03:52:48 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp x.x.x.x:8080: connect: connection refused"

why i set the port 8081 in .env , but it is 8080 in error log?

thanks

**Comment by byliuyang** [comment]
@cx2c Please join our slack and elaborate the issue in #short channel. This is no enough information in the issue. Thanks!
