### ISSUE TITLE
Repeatedly request sign in 

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#192]
The sign in dialog shows up repeatedly when trying to create a short link. This happens when user's Github email is empty.

<img width="762" alt="Screen Shot 2019-09-30 at 10 33 19 PM" src="https://user-images.githubusercontent.com/3537801/65936706-59c17a00-e3d2-11e9-8c63-7a81fa333bbc.png">

**Comment by lawaloy** [comment]
I will like to work on this issue

**Comment by byliuyang** [comment]
@lawaloy Thank you!

**Comment by byliuyang** [comment]
@lawaloy Please join this Slack channel to discuss bugs, dev environment setup, tooling, and coding best practices.

**Comment by byliuyang** [comment]
@lawaloy May I have your email?

**Comment by lawaloy** [comment]
Lasei_1992@yahoo.com

Kind Regards,

Oluwaseyi Lawal  
 
  On Fri, Oct 11, 2019 at 12:05 PM, Harry Liu<notifications@github.com> wrote:   
@lawaloy May I have your email?

**Comment by lawaloy** [comment]
> @lawaloy May I have your email?

I was unable to see the link because your message is coming to my email box directly.

**Comment by byliuyang** [comment]
I invited you to Slack and you joined already.

**Comment by lawaloy** [comment]
Okay, thanks. I'm still working on that task.  
 
  On Sat, Oct 12, 2019 at 12:46 PM, Harry Liu<notifications@github.com> wrote:   I invited you to Slack and you joined already.

**Comment by byliuyang** [comment]
Hi @lawaloy, this bug involves redesigning the database tables and changing Github OAuth & Authentication logic. It's very complex. Do you want to try a [different issue](https://github.com/byliuyang/short/issues/246) instead? I am planing to take on this.

**Comment by lawaloy** [comment]
Okay, That is fine.

**Comment by lawaloy** [comment]
Okay, that is fine. I will take on another issue

**Comment by byliuyang** [comment]
@lawaloy Thank you!

**Comment by byliuyang** [comment]
Migrate from email to user ID.
