### ISSUE TITLE
Add React component to show all short links created by the user

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#193]
Currently, users can't see all the short links they created.

<img width="1299" alt="Screen Shot 2019-09-30 at 10 37 51 PM" src="https://user-images.githubusercontent.com/3537801/65936901-f84ddb00-e3d2-11e9-93b3-aca552a69a67.png">

Add React component with dummy data to show all the linked created by the user after he, she or they signed in.

**Comment by shade34321** [comment]
I'd like to try this if this is still available but I'll probably have lots of questions.

**Comment by byliuyang** [comment]
@shade34321 Sounds good. Please feel free to ask question or suggest refactor.

**Comment by byliuyang** [comment]
@shade34321 Please join this [Slack channel](https://s.time4hacks.com/r/short-slack) to discuss bugs, dev environment setup, tooling, and coding best practices.

**Comment by shade34321** [comment]
Oh man, I never saw this message. I"ll see if I can work on it later this weekend or next. I'm sorry!

**Comment by byliuyang** [comment]
The component should be hidden by feature toggle by default.

**Comment by JackieYJC** [comment]
I can take this task. Seems like a very important feature to the user!

**Comment by JackieYJC** [comment]
For this task, does the UI need to be in place? In other words, is the expectation that after it is done, whoever works on the backend API for read/write to the database can just populate the component and enable the feature to live?

**Comment by byliuyang** [comment]
@JackieYJC Mostly yes. For now, we just populate fake data and turn off the feature toggle. We will have to make small change to our frontend data service to make sure it pulls data from real backend.

**Comment by JackieYJC** [comment]
> @JackieYJC Mostly yes. For now, we just populate fake data and turn off the feature toggle. We will have to make small change to our frontend data service to make sure it pulls data from real backend.

Gotcha, I'm considering using tables from this source: https://material-ui.com/components/tables/

**Comment by byliuyang** [comment]
@JackieYJC Prefer building the components ourselves so that we:
1) easily customize the styles
2) add new features
3) learn how the internals work

**Comment by JackieYJC** [comment]
@byliuyang Yes, I don't intend to copy-and-paste anything. Just learn their tricks and apply it here. A table is a table 😛

**Comment by byliuyang** [comment]
@JackieYJC Let's split this issue into few PRs:

1) The reusable table component
2) The reusable pagination component
3) The `ShortLinks`  component
4) Fake  `ShortLinkService`
5) Integrate `ShortLinks`  component and `ShortLinkService` in Home page with feature toggle turned off.

**Comment by rohithbalaji123** [comment]
@byliuyang I am wondering if we should fix column width of the tables.

![columnWidth](https://user-images.githubusercontent.com/18581705/80297149-44f96900-879e-11ea-8320-136e7f2495f4.gif)

**Comment by byliuyang** [comment]
@rohithbalaji123 Let's open an new issue for it!
