### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#197]
Currently, code coverage is only 55%. We want to add more unit tests to the backend APIs to improve developer confidence. Refactor may be needed to improve the testability of the code. Let's do it incrementally.

## Success criteria
Increase code coverage for `app/usecase/url` package to 100%.

**Comment by KamalashreeNagaraj** [comment]
I would like to give this a try. Would any increase in code coverage be welcome? Or it has to cross 80%?

**Comment by dedifferentiator** [comment]
@KamalashreeNagaraj forgot to mark that I'm already working on coverage of _app/adapter/graphql/resolver_ directory, but I believe there are many other parts to cover, so it's not a problem at all

**Comment by KamalashreeNagaraj** [comment]
Sure. Will work on another package. 
Also, I see utility files like `app/adapter/graphql/parser/time.go`. Do you need tests for these or you're ignoring them from coverage?

**Comment by KamalashreeNagaraj** [comment]
I would like to work on `app/usecase/url`. Is that okay?

**Comment by byliuyang** [comment]
@KamalashreeNagaraj  We want to cover all exported functionalities eventually in all go packages. Let's do it incrementally. Does 65% to 70% for this pull request sounds good to you? Please refactor existing code to make them testable when needed.

@dedifferentiator @KamalashreeNagaraj  I am sorry for the tech debts. I was in rush when adding some features to get started. Every feature should have their automated tests. I will read Working Effectively with Legacy Code from now on to explore the ways of improving maintainability.

**Comment by byliuyang** [comment]
@KamalashreeNagaraj Surely.

**Comment by dedifferentiator** [comment]
@byliuyang wouldn't it be better to use pointer to URL in receiver arg? Same question towards other methods in this file.

https://github.com/byliuyang/short/blob/0b24c39adffd8bd06106921bf85f7c811fb34ede/app/adapter/graphql/resolver/url.go#L12-L14

**Comment by byliuyang** [comment]
@dedifferentiator In term of semantics, I remember the consultant taught during a training, pointer receiver means that we are mutation the field. It doesn't seem that we are mutating any thing in this function. 

Can't find the evidence in [Advanced Ultimate Go Training repo](https://github.com/ardanlabs/gotraining/blob/master/topics/courses/go/README.md). Please let me know if you disagree.

**Comment by dedifferentiator** [comment]
@byliuyang as far as I know you have to pass pointer to an object if you want to modify (mutate) that object or constantly get actual value of it, but not necessarily in that function, for instance you want to pass this value somewhere further. I would agree if you wouldn't return pointer to a string, because in that case there's no practical benefit from it. I mean you return pointer to the copied object, which doesn't make much sense, except of saving some bytes of course.

Or I don't understand usage of this pointer later :)

**Comment by dedifferentiator** [comment]
Also I will experience some difficulties with testing in that case, because I am unable to predict what pointer I will receive

**Comment by byliuyang** [comment]
GraphQL forced me to return pointer if I want to make this field optional 😭

**Comment by dedifferentiator** [comment]
@byliuyang a-ha, that explains a lot, but we have one of two: pass pointer into method or leave the methods untestable

**Comment by byliuyang** [comment]
I am trying to understand why passing value will make this function untestable.

**Comment by dedifferentiator** [comment]
@byliuyang 
```
func TestURL_Alias(t *testing.T) {
	urlTest := URL{url: struct {
		Alias       string
		OriginalURL string
		ExpireAt    *time.Time
		CreatedBy   *entity.User
		CreatedAt   *time.Time
		UpdatedAt   *time.Time
	}{Alias: "TestAlias"}}
	fmt.Printf("%p\n", &urlTest.url.Alias) // 0xc0000134c0
	fmt.Printf("%p", urlTest.Alias())      // 0xc000013500
        ...
```
Of course I can dereference pointer, but it won't be a fair test, in my opinion.
Although after I said it it doesn't sound so persuasively.

**Comment by dedifferentiator** [comment]
By the way, could you give me a tip how to create fake objects for testing like Mutation, Resolver, honestly I cannot find a good way how to create them :(

**Comment by byliuyang** [comment]
I prefer having unit tests for all business logics but add integration tests for API endpoints instead. What are your thoughts?

**Comment by dedifferentiator** [comment]
@byliuyang great option I think

**Comment by KamalashreeNagaraj** [comment]
Also, I see that code coverage stage can be run only on master. I feel it would be better to allow this on branches too.

**Comment by byliuyang** [comment]
@KamalashreeNagaraj You can run the following command to obtain the coverage:
```bash
go test -coverprofile=coverage.txt ./...
```
 I'll add it to the README file.

**Comment by byliuyang** [comment]
@dedifferentiator @KamalashreeNagaraj Please join this [Slack channel](https://s.time4hacks.com/r/short-slack) to discuss bugs, dev environment setup, tooling, and coding best practices.

**Comment by byliuyang** [comment]
![1D3AF4AD-5367-4104-8529-789F018A2587](https://user-images.githubusercontent.com/3537801/66939084-3f54e680-eff7-11e9-8b8e-71f23345cc4b.jpeg)

**Comment by byliuyang** [comment]
Here are the testing best practices: https://api.short-d.com/r/testing

**Comment by dedifferentiator** [comment]
@byliuyang 

> Here are the testing best practices: https://api.short-d.com/r/testing

Wow, I was looking for this article my whole life

**Comment by byliuyang** [comment]
@dedifferentiator Let’s together refactor & implement this article for Short to make it reliable and easy to maintain! This also serves as an opportunity for you to try them in practice!

**Comment by KamalashreeNagaraj** [comment]
Hey, sorry. Had been busy the past few days. The slack channel link you shared is returning a `404 not found`.

Thank you for sharing the article.

Let me know if there is anything I can contribute with 🙂.

**Comment by byliuyang** [comment]
Hi @KamalashreeNagaraj , I reactivated the link. Please try again.

**Comment by KamalashreeNagaraj** [comment]
oh, it still says the same 
![image](https://user-images.githubusercontent.com/13076286/67137996-2187bb80-f25b-11e9-878e-db000b793aae.png)

**Comment by byliuyang** [comment]
Oh, sorry @KamalashreeNagaraj. I renamed the link to: `https://short-d.com/r/slack` instead of `https://short-d.com/r/short-slack` for simplicity

**Comment by byliuyang** [comment]
This one is unpractical to achieve. Closing now.
