### ISSUE TITLE
Add GraphQL API to show aliases created by the current user

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#200]
Currently, users can't see all the short links they created.

<img width="1299" alt="Screen Shot 2019-09-30 at 10 37 51 PM" src="https://user-images.githubusercontent.com/3537801/65936901-f84ddb00-e3d2-11e9-93b3-aca552a69a67.png">

Add GraphQL API to show all the linked created by the user after he, she or they signed in.

**Comment by obukhov** [comment]
Can I take this?

**Comment by byliuyang** [comment]
@obukhov Surely!

**Comment by byliuyang** [comment]
@obukhov Please join this [Slack channel](https://s.time4hacks.com/r/short-slack) to discuss bugs, dev environment setup, tooling, and coding best practices.

**Comment by princejha95** [comment]
Looks interesting issue to me. Can i take this ?

**Comment by dawntomm** [comment]
Can i take this ?

**Comment by kapillamba4** [comment]
```
type Retriever interface {
	GetURL(alias string, expiringAt *time.Time) (entity.URL, error)
	GetURLsByUser(user entity.User) ([]entity.URL, error)
}

```

GraphQL Schema:
```
type AuthQuery {
	URL(alias: String!, expireAfter: Time): URL
	changeLog: ChangeLog!
	listURLs: [URL!]!
}

```

@byliuyang
