### ISSUE TITLE
Add query parameter to automatically fill in long URL.

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#205]
## Scenario
After the user clicks the icon of the [Chrome Extension](https://github.com/byliuyang/short-ext)
<img width="226" alt="Screen Shot 2019-10-07 at 8 47 10 AM" src="https://user-images.githubusercontent.com/3537801/66327086-1342b280-e8df-11e9-8cae-90e6bed541da.png">
 , the extension will grab the URL of the current page and redirect the user to the app’s home page with `&long_link=http://the_current_page_url` appended in the URL. The page automatically fill in the URL of the current page, and move the cursor to the alias text field, waiting for the user to create a the short link.

## Success criteria
The page automatically fill in the URL of the current page if the URL has `&long_link=http://the_current_page_url`appended. It then move the cursor to the alias text field, waiting for the user to create a the short link.

**Comment by byliuyang** [comment]
@rohanrk Surely!

**Comment by byliuyang** [comment]
@rohanrk Please join this [Slack channel](https://s.time4hacks.com/r/short-slack) to discuss bugs, dev environment setup, tooling, and coding best practices.

**Comment by JackieYJC** [comment]
Would love to work on this!

**Comment by byliuyang** [comment]
Hi @JackieYJC , the progress of this issue is now tracked here: https://github.com/byliuyang/short/projects/1
