### ISSUE TITLE
[Feature] Add private / public option when creating short link

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#235]
Currently, all the short links created are private to their authors. We want to encourage people to share some of their short links with others to give back to the community.

To achieve this:

- Add a toggle button on the short link creation panel  to allow use to specify whether the short link created will be publicly available. By default, the short link should be private by default.
- Add a database attribute to indicate whether the short link is public.
- Update GraphQL short link creation API with new argument

Please create a separate issue for each litem listed here and link them back to this one.

**Comment by Coteh** [comment]
I can give this one a try.

**Comment by Coteh** [comment]
Issues created.
