### ISSUE TITLE
Create RESTful search API in Go

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#260]
Please support async and request cancellation based on the examples provided in the comment.
#238

**Comment by byliuyang** [comment]
Here are some references on goroutine:

1. https://talks.golang.org/2012/concurrency.slide#1
2. https://blog.golang.org/context
3. https://blog.golang.org/pipelines

**Comment by lucifercr07** [comment]
@byliuyang will like to take it up

**Comment by lucifercr07** [comment]
Api: /api/search
Header: Auth token
Query params: 
1. Paging: query params `page.size = 10, page.number = 1` (static for now)
2. type: private or public

**Comment by byliuyang** [comment]
@lucifercr07 For now, we can hard code `page.size`. Let open an issue to track `custom page` size feature. Please document the API endpoint with Swagger ( OpenAPI 3 ). Let's also open an new issue to configure Dredd, a language-agnostic command-line tool for validating API description document against backend implementation of the API.

**Comment by byliuyang** [comment]
Let's scope this feature down to easy development progress:

1) Create RESTful API placeholders in `adapter/routing` package
2) Create repository interfaces in `usecase/repo` package. Those interfaces are purely responsible for database access and have nothing to do with search.  Create search functionalities (are dependent on `usecase/repo` interfaces) in `usercase/search` package.
3) Call search use cases in the RESTful API.

Hope this helps.

**Comment by luisfmelo** [comment]
Is this being developed?

**Comment by lucifercr07** [comment]
@luisfmelo yes

**Comment by byliuyang** [comment]
Hi @luisfmelo are there any other issue you are interested?

**Comment by byliuyang** [comment]
For now, please only search private alias

**Comment by dawntomm** [comment]
I will work on it

**Comment by byliuyang** [comment]
https://github.com/short-d/short/tree/search

**Comment by byliuyang** [comment]
Maybe also consider how to build our own Elasticsearch.

**Comment by byliuyang** [comment]
https://www.elastic.co/elasticsearch/

**Comment by byliuyang** [comment]
https://www.educative.io/courses/grokking-the-system-design-interview/xV9mMjj74gE

**Comment by arberiii** [comment]
During my research I found those articles useful:
- The above link mention (Designing Twitter Search)
- https://www.elastic.co/blog/found-elasticsearch-from-the-bottom-up
- https://www.elastic.co/blog/found-sizing-elasticsearch
- https://www.elastic.co/blog/found-elasticsearch-top-down

**Comment by byliuyang** [comment]
Discussed offline. Due to the complexity of the search engine, let's simplify and focus on implement concurrent search for users and urls for now.

**Comment by byliuyang** [comment]
# To be done now
1) Build the simple search API for user to search their short links

# Future Plan
2) Extend the search API to support searching both short link & users concurrently
3) Extract out search into a  generic cloud service.
