### ISSUE TITLE
Create feature toggle service

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#261]
Feature toggle allows us to:
- Temporarily turn off a feature until it's ready for launch
- Performance A / B testing to validate different designs of a feature

**Comment by byliuyang** [comment]
https://martinfowler.com/articles/feature-toggles.html

**Comment by byliuyang** [comment]
![backend](https://user-images.githubusercontent.com/3537801/67156399-e032f280-f2d2-11e9-9ab8-43dbaa6c1f42.png)
https://github.com/byliuyang/toggle

**Comment by alldroll** [comment]
An interesting task!
I would like to implement this service, but I have a couple of questions...

* How exactly ProbabilisticToggle should work? Is it going to use some strategy as [Epsilon greedy](http://stevehanov.ca/blog/?id=132) or [Exp3](https://jeremykun.com/2013/11/08/adversarial-bandits-and-the-exp3-algorithm/)? If not, we could just use modulo arithmetic on a user ID for A/B splitting.
* Is it going to be a separate microservice or part of the application?
* How are we going to decide who has access to the feature control panel? Is it going to be a special role?

**Comment by byliuyang** [comment]
Hi @alldroll, to answer your questions:

> * How exactly `ProbabilisticToggle` should work? Is it going to use some strategy as [Epsilon greedy](http://stevehanov.ca/blog/?id=132) or [Exp3](https://jeremykun.com/2013/11/08/adversarial-bandits-and-the-exp3-algorithm/)? If not, we could just use modulo arithmetic on a `user ID` for `A/B` splitting. (as I understood, all clients are registered)

Machine Learning optimization is definitely a plan in the future! For now, to simplify, we generate unique identifier for each user visiting the site and save it in the cookie. The ID will be tied to the users account after they signed in. `For probabilisticToggle`, the first time the user see the page, the feature toggle will decided which feature this user will see and record that user's unique ID and upgrade the toggle to `UserToggle` at the background.



> * Is it going to be a separate microservice or part of the application?
This will be a separate microservice so that future project and the community developers have easy access to it: https://github.com/byliuyang/toggle. Logically, it's not a unique need of Short.

> * How are we going to decide who has access to the feature control panel? Is it going to be a special role?

Since it's a separate microservice, it should have its separate access control list.

I am also planning to decouple single sign on from Short's repo and reuse it for other services.

**Comment by byliuyang** [comment]
I haven't finished the design of analytics part it.

**Comment by alldroll** [comment]
Ok, let me know when it will be ready!

**Comment by byliuyang** [comment]
@alldroll I'll setup up the project in order to get started.
