### ISSUE TITLE
Add sign out option in the header

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#305]
Currently, user cannot not sign out or switch account after he, she or they signed in.

**Comment by jscodelover** [comment]
I want to work on this issue.

**Comment by jscodelover** [comment]
Can you tell is this issue needs to be done from backend side also? And the slack link which you have provided in the readme is not working. I have a few more doubts.

**Comment by byliuyang** [comment]
Hi @jscodelover , to simplify, we can just add a signout button and delete the auth token in the cookie.

**Comment by byliuyang** [comment]
Hi @jscodelover , the Slack link should be fixed now.

**Comment by jscodelover** [comment]
Thanks, I will join the slack

**Comment by nathan815** [comment]
@jscodelover Are you working on this still?

**Comment by byliuyang** [comment]
@nathan815 It seems that this feature has not been proactively working on for almost a month. It can be reassigned. Are you interested in working this feature?

**Comment by nathan815** [comment]
@byliuyang I am. Seems like this is a good one to start with :)

I noticed there was a merged PR regarding the sign out button but the commit got reverted. Should I start from that?

**Comment by kapillamba4** [comment]
@byliuyang May i work on this?

**Comment by byliuyang** [comment]
Yes
