### ISSUE TITLE
Create status page service

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#348]
It just very difficult to prevent bugs or outages from happening.
A status service ( https://status.circleci.com, https://www.githubstatus.com/ ) should be created to

1) signal users about any outages
2) allow users to subscribe any updates when services got fixed

This page can be implemented with fake data for now

**Comment by Tlac** [comment]
I'll take this on!

**Comment by Tlac** [comment]
Harry and I have decided on having this feature on its own service

**Comment by byliuyang** [comment]
Here is the project proposal: http://s/status
