### ISSUE TITLE
Add change log modal

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#353]
**Is your feature request related to a problem? Please describe.**
Many updates are made to Short. Users don't know them.

**Describe the solution you'd like**
Add updates modal to remind users. Once users closed the modal for this release, it shouldn't automatically popup again. Users should be able to reopen it by clicking on a button in the footer.
 
![image](https://user-images.githubusercontent.com/3537801/69011841-ae3d9c00-0923-11ea-9821-24ea5e0318c6.png)

**Comment by jonjiang1** [comment]
I'll be taking this! Please assign it to me
