### ISSUE TITLE
[Refactor] Move construction code closer to struct definition

### ISSUE THREAD

**Issue by dawntomm** [short-d/short#420]
**What is the problem?**
Constructor is put at bottom of code which makes it hard to find for developers.

**Your solution**
Put constructor close to struct definition.

**Alternatives considered**
Leave constructor as it is, because it's less likely to be changed.

**Comment by byliuyang** [comment]
Discussed on Slack. As a team, we decided to leave this piece of the code to the bottom of the file. Closing this issue.
