### ISSUE TITLE
[Feature] Add documentation for Google sign in feature

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#483]
**What is the problem?**
There is no documentation on how to configure Google sign in feature.

**Your solution**
Add documentation on how to setup Google sign in API and on how to configure environmental variables. [.env.dist](https://github.com/short-d/short/blob/master/backend/.env.dist) should also be updated.

**Comment by dawntomm** [comment]
I will work on this issue

**Comment by byliuyang** [comment]
@dawntomm Cool!
