### ISSUE TITLE
[Feature] Add integration tests for Google identityProvider

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#492]
**What is the problem?**
Currently, there is no integration test for Google OAuth API. This results in low test coverage. People can accidentally break the code without knowing.

**Your solution**
Add integration tests for Google identityProvider.

**Additional context**
https://github.com/short-d/short/blob/master/backend/app/adapter/google/identityprovider.go
Please carefully read every single page of [this slide](https://martinfowler.com/articles/microservice-testing/) from Martin Flower to brush up your testing skills!

**Comment by dawntomm** [comment]
I will take this
