### ISSUE TITLE
[Feature] Rewrite facebook API package

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#494]
**What is the problem?**
Existing [facebook package](https://github.com/short-d/short/tree/master/backend/app/adapter/facebook) was checked in for a rush bug fix. The code is not held to the standard as of [google package](https://github.com/short-d/short/tree/master/backend/app/adapter/google). 

**Your solution**
Research Facebook APIs and rewrite this package based on the coding standard of `google` package. Integration tests are must.

**Comment by dawntomm** [comment]
I will take this
