### ISSUE TITLE
[Refactor] Extract create short link section into its own fragment 

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#497]
**What is the problem?**
The internal implementation of create short link fragment is hard coded inside Home page component. This not only makes the code more complex to understand but also prevent the fragment from being reused in other part of the application.

**Your solution**
Extract create short link section into its own fragment and replace with corresponding code inside Home page component with the new fragment.

**Additional context**
https://github.com/short-d/short/blob/master/frontend/src/component/pages/Home.tsx#L184-L221

**Comment by JackieYJC** [comment]
Hi can I pick up this task?
