### ISSUE TITLE
[Feature] Remove Get Chrome Extension component when user already installed the extension.

### ISSUE THREAD

**Issue by rohithbalaji123** [short-d/short#522]
**What is the problem?**
The "Get Chrome Extension" component is being shown even after the user installs the extension.

**Your solution**
Hide the component once the browser already has the extension.
BJury's answer in [here](https://stackoverflow.com/questions/6293498/check-whether-user-has-a-chrome-extension-installed) explains a way to achieve this.

**Alternatives considered**
Probably show a close button to hide the component.

**Additional context**
In my opinion, the component can be hidden when the browser already has the extension, and even when the user does not choose to install the extension, there can be an 'x' button in the end of the component to close it.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18581705/76119018-7e222200-6014-11ea-9aa9-631ef6acad38.png">

**Comment by byliuyang** [comment]
Hi @rohithbalaji123 , are you interested in prototyping this feature?!

**Comment by rohithbalaji123** [comment]
Hey @byliuyang , sure. I would like to give it a try over this weekend.

**Comment by byliuyang** [comment]
@rohithbalaji123 Thank you! I prefer automatically hide the flash message. Probably message passing.
