### ISSUE TITLE
[Feature] Allow generated link to be copied into user's clipboard

### ISSUE THREAD

**Issue by rohithbalaji123** [short-d/short#527]
**What is the problem?**
Every time user wants to generate a short link and share it with their fellows, they have to select the link text and then copy.

**Your solution**
Instead, the generated the link can be automatically copied to clipboard.

**Alternatives considered**
Instead, there can also be a button which on clicking will copy the generated link to clipboard.

**Additional context**
Instead of the current message "You can now paste `<link>` in your browser to visit.", we can have something like "Please visit `https:/short-d.com/r/<alias>` or `s/<alias>`(if you have short-d chrome extension) in your browser". Allowing this text to be copied will also publicize the existence of such an extension. Your thoughts?

**Comment by byliuyang** [comment]
Auto copy to clipboard and show a toast message at the bottom of the page to let them know it's copied. 

![image](https://user-images.githubusercontent.com/3537801/76137454-f9bea780-5ff1-11ea-922d-ec60a0710208.png)

**Comment by rohithbalaji123** [comment]
@byliuyang , I would like to take this up.
