### ISSUE TITLE
[BUG] invalid extension id: 'extension_id' error on staging

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#545]
**Describe the bug**
When visiting [staging](https://staging.short-d.com) website,  `invalid extension id: 'extension_id'` error is thrown in developer console.
<img width="1440" alt="Screen Shot 2020-03-09 at 10 16 12 PM" src="https://user-images.githubusercontent.com/3537801/76282021-c8ddad00-6253-11ea-878d-13cee537f449.png">

**To Reproduce**
1. Open [staging](https://staging.short-d.com) website
2. Open developer console

**Expected behavior**
The console should show `could not establish connection` error instead to show the website is trying to ping the extension.
![image](https://user-images.githubusercontent.com/3537801/76282204-4dc8c680-6254-11ea-976f-9b466a173ae8.png)

**Comment by kapillamba4** [comment]
Experiencing this issue on mozilla as well (on dev environment)
![Screen Shot 2020-03-10 at 10 29 28](https://user-images.githubusercontent.com/20877996/76282688-6241a900-62be-11ea-9c1d-a7e96923af25.png)

**Comment by byliuyang** [comment]
Here are some hints on resolving this issue:
1) Remove `REACT_APP_CHROME_EXTENSION_ID` from [.env.production](https://github.com/short-d/short/blob/master/frontend/.env.production), [.env.staging](https://github.com/short-d/short/blob/master/frontend/.env.staging), and [.env.test](https://github.com/short-d/short/blob/master/frontend/.env.test)
2) Update CI pipeline to retrieve `REACT_APP_CHROME_EXTENSION_ID` from CI runtime (https://github.com/short-d/short/blob/64b1a6201b5e8bca223776d20c031c8806f9f3f0/.drone.yml#L27, https://github.com/short-d/short/blob/64b1a6201b5e8bca223776d20c031c8806f9f3f0/.drone.yml#L11)
3) Add `CHROME_EXTENSION_ID` in [CI repo settings](https://ci.time4hacks.com/short-d/short/settings)
