### ISSUE TITLE
[Feature] Create backend GraphQL APIs for change logs

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#566]
**What is the problem?**
Change log modal is rendering dummy logs.

**Your solution**
Create backend GraphQL APIs to query change logs for a given user.

**Comment by byliuyang** [comment]
https://github.com/short-d/short/pull/530

**Comment by byliuyang** [comment]
Here are some steps need to create this API:

1. Propose GraphQL API schema for change logs on this issue.
2. Propose new DB tables for change logs on this issue.
3. Create DB migrations, create corresponding repositories, and add DB integration tests.
4. Create a `changelog` package within `usecase` package and add the required usecase with unit tests.
5. Add GraphQL schema and resolvers.
6. Hook up the GraphQL API with the usecase.
7. Add required code in `wire.go` required for dependency injection
8. Integrate change log API with the frontend

**Comment by kapillamba4** [comment]
**GraphQL schema:**
```
type AuthQuery {
	changeLog(): ChangeLog
}

type AuthMutation {
  	updateLastSeenChangeLogUser(): Time
}
```

**Columns for DB table "change_log":**
![Screenshot from 2020-03-21 23-21-44](https://user-images.githubusercontent.com/20877996/77233047-e4897180-6bca-11ea-9185-f044524c633b.png)

**12_add_changelog_table.sql**
```
-- +migrate Up
CREATE TABLE "change_log"
(
    "id"            CHARACTER VARYING PRIMARY KEY,
    "title"         CHARACTER VARYING VARCHAR,
    "summary"       CHARACTER VARYING VARCHAR,
    "releasedAt"    TIMESTAMP WITH TIME ZONE
);

-- +migrate Down
DROP TABLE "change_log";
```

**13_add_last_seen_changelog_column.sql**
```
-- +migrate Up
ALTER TABLE "user" ADD last_seen_changelog TIMESTAMP WITH TIME ZONE;

-- +migrate Down
ALTER TABLE "user" DROP last_seen_changelog;
```
@byliuyang

**Comment by byliuyang** [comment]
# GraphQL schema

```graphql
type AuthQuery {
  changeLog: ChangeLog!
}

type ChangeLog {
    changes: [Change]!
    lastViewedAt: Time
}

type Change {
  id: ID!
  title: String
  summaryMarkdown: String
  releasedAt: Time!
}

input ChangeInput {
  title: String
  summaryMarkdown: String
}

type AuthMutation {
  viewChangeLog():  Time!
  createChange(change: ChangeInput): Change!
}
```

# DB tables

## change_log
| Column      | Type                     | Default    | Constraints        |
|-------------|--------------------------|------------|--------------------|
| id          | CHARACTER VARYING(5)     | no default | primary key unique |
| title       | CHARACTER VARYING(100)   | no default |                    |
| summary     | TEXT                     | no default |                    |
| released_at | timestamp with time zone | no default |                    |

// user_change_log
| Column         | Type                     | Default    | Constraints            |
|----------------|--------------------------|------------|------------------------|
| user_id        | CHARACTER VARYING(5)     | no default | foreign key => user.id |
| last_viewed_at | timestamp with time zone | no default |                        |

**Comment by kapillamba4** [comment]
@byliuyang  createChange() cannot be written right now until admin dashboard is completed...we would have to manually add changelog to database...user_id is not populated right now...may I add another column email to user_change_log...what would happen if email changes?

**Comment by byliuyang** [comment]
@kapillamba4 Let's keep user ID but just not make it `foreign key` yet. I am now working hard on `user email` to `user ID` migration ( hopefully will be done soon ).

`createChange` is needed. We can use [Insomnia](https://insomnia.rest/graphql/) to invoke `createChange` API before the admin dashboard is done. Your next ticket will be creating the admin dashboard and flesh out change log section of it!!!:

<img width="1680" alt="Screen Shot 2020-03-21 at 6 48 57 PM" src="https://user-images.githubusercontent.com/3537801/77240568-c3ae2580-6ba4-11ea-92ab-46257e2f66f4.png">

**Comment by rohithbalaji123** [comment]
@byliuyang @kapillamba4 Hey, I was reading through the thread and had a couple of doubts.
- Are we showing the change logs for newly registered users?
- If a user is logging in after a long time, are we showing the whole list of change logs?

**Comment by byliuyang** [comment]
@rohithbalaji123 We only show the ones they haven't seen yet by default. When clicking on `view all` button, we will all changes for now. In the future, we want to have pagination.

@rohithbalaji123 We should only show the changes happened after the user created his or her account.

**Comment by rohithbalaji123** [comment]
Ohkay, great. If I login after say, an year, will I see all the changes happened since then? Or are we limitting to any threshold number of items in the list?

**Comment by byliuyang** [comment]
@rohithbalaji123 We should have some threshold.

**Comment by byliuyang** [comment]
Done.
