### ISSUE TITLE
[BUG] Alias Not Available modal keeps popping up when not closed with 'x' button

### ISSUE THREAD

**Issue by rohithbalaji123** [short-d/short#582]
**Describe the bug**
Alias Not Available modal keeps popping up for every change in input text when not closed using the 'x' button in the modal.

**To Reproduce**
1. Go to short-d.com, type a Long Link and an unavailable alias and click on `Create Short Link`
Eg: Long Link => `https://github.com`, Custom Short Link => `gg`
2. An error modal showing that the alias is not available will be shown. Click anywhere in the page except the 'x' button in the modal. The error modal will disappear.
3. Now try to edit either the long link or the alias. The modal pops up again even when the submit button is not clicked.

**Expected behavior**
The modal should not appear once closed by any means(even when closed by clicking elsewhere in the page).

**Additional context**
Also, we are currently able to navigate through UI using keyboard and type in inputareas when the error modal is visible. Is this an expected behavior?

**Comment by byliuyang** [comment]
@rohithbalaji123 I don't think users should be allowed the interact before modal is closed.

**Comment by byliuyang** [comment]
The modal implementation turns out to be incorrect.
