### ISSUE TITLE
[BUG] Fix auth token short expiration period bug

### ISSUE THREAD

**Issue by JackieYJC** [short-d/short#623]
**Describe the bug**
Currently after user sign in for 24 hours, the auth token expires and the user will see 'Unknown Error' alert when they create the short link. To fix this issue, user would have to manually sign out and re-sign in. However, we never tell user how to re-sign and all they see is the 'Unknown Issue' alert. 

**To Reproduce**
1. Sign in to short website
2. Wait for 24 hours
3. Visit short website to create short link
4. The alert should show up once you click create button

**Expected behavior**
#### Stage 1
- User doesn't need to re-sign in within one week
- User whose auth token has expired are asked to re-sign (instead of the error alert)
#### Stage 2
- Ideally we should consider automatically extending the expiration date if the user visit short-d.com within a week, in order to provide a seamless user experience.

**Screenshots**

![1](https://user-images.githubusercontent.com/13726179/78457763-72e90300-7661-11ea-9627-da00d70d7731.png)

**Alternatives Considered**
Change the 'Unknown Error' message to 'Please re-sign in'.
Pro: Easy to fix
Con: Poor user experience (every 24 hrs user will have to re-sign in, very annoying), make the user feel the team is not actively fixing the issue. 

**Additional context**
Where 24 hour expiration is set: https://github.com/short-d/short/blob/master/backend/dep/wire.go#L44

**Comment by arberiii** [comment]
This issue is fixed! The error message is changed at [PR 638](https://github.com/short-d/short/pull/638), while the expiration period is a set to environment variable at [PR 665](https://github.com/short-d/short/pull/665).

**Comment by byliuyang** [comment]
Stage 2 is not done yet: Ideally we should consider automatically extending the expiration date if the user visit short-d.com within a week, in order to provide a seamless user experience.

**Comment by byliuyang** [comment]
Fine. I created a separate task on meistertask
