### ISSUE TITLE
[Feature] Integrate change log api with the frontend

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#643]
**What is the problem?**
[Change log service](https://github.com/short-d/short/blob/master/frontend/src/service/ChangeLog.service.ts) in the frontend is rendering dummy data hard-coded. 

**Your solution**
Integrate change log service with [GraphQL API](https://github.com/short-d/short/blob/033ccc686046e12f72cdfdbdd3b829bebfab88e1/backend/app/adapter/graphql/schema.go#L17) so that change log modal works as a whole.

**Comment by kapillamba4** [comment]
email must be mappped to user id before this issue

**Comment by byliuyang** [comment]
@kapillamba4 How about we use email as user ID for now?

**Comment by byliuyang** [comment]
The ID migration is taking more time than I expected.

**Comment by byliuyang** [comment]
We pass in `entity.User` to the use case instead of `email` itself to easy changes.

**Comment by byliuyang** [comment]
Done.
