### ISSUE TITLE
[Feature] Add GraphQL mutation api for view change log

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#644]
**What is the problem?**
Currently, there is no explicitly way to confirm whether and when did user view the change log.

**Your solution**
Add GraphQL api to record the time the user viewed the change log.

```graphql
type AuthMutation {
        ...
        viewChangeLog(): Time
}
```

**Comment by kapillamba4** [comment]
So this api will be called when user closes the changelog modal?

**Comment by byliuyang** [comment]
@kapillamba4 I think should be when the user open the modal.
