### ISSUE TITLE
[Refactor] Move envconfig into app framework

### ISSUE THREAD

**Issue by byliuyang** [short-d/short#649]
Current [envconfig](https://github.com/short-d/short/tree/master/backend/envconfig) in located in Short's repo. However, it's reusable across all microservices.

Define `EnvConfig` interface in [fw](https://github.com/short-d/app/tree/master/fw) and create implementation here: https://github.com/short-d/app/tree/master/modern

**Comment by byliuyang** [comment]
Example PR: https://github.com/short-d/app/pull/71

**Comment by arberiii** [comment]
The envconfig pkg uses unit pkg, should we also move that one?

**Comment by byliuyang** [comment]
@arberiii Yes, please. As an internal package of app framework. We may want to complete refactor app framework after you back to full strength!

**Comment by byliuyang** [comment]
https://github.com/short-d/app/pull/80
