### ISSUE TITLE
[Refactor] Update URL's Create method name to CreateURL

### ISSUE THREAD

**Issue by oatovar** [short-d/short#698]
**Issue**
Currently, the [URLFake](https://github.com/short-d/short/blob/master/backend/app/usecase/repository/url_fake.go#L22) and [URLSql](https://github.com/short-d/short/blob/master/backend/app/adapter/db/url.go#L41) structs implement the URL interface which has a method named `Create`. This should be changed to `CreateURL` so that implementing structs cleary express what the function does.

**Your solution**
Refactor so that `Create` is changed to `CreateURL`  in the [URL interface](https://github.com/short-d/short/blob/master/backend/app/usecase/repository/url.go#L9). The interface implementations will also need to be updated as well.

**Comment by byliuyang** [comment]
Thank you!
