### ISSUE TITLE
[Refactor] [UI] Fix column widths in Favorites section

### ISSUE THREAD

**Issue by rohithbalaji123** [short-d/short#702]
**What is frustrating you?**
When traversing between pages, the column widths in favourites section changes depending on the length on long links making the alias column keep moving.

**Your solution**
Allot a percentage of table widths for each column to make sure the column remain in the same position irrespective of the length of the long links.

![columnWidth](https://user-images.githubusercontent.com/18581705/80297395-4035b480-87a0-11ea-9b45-9e6c086095f9.gif)

**Comment by Coteh** [comment]
@rohithbalaji123 Should there be any special rules for wrapping URLs? (e.g. should TLD names never be able to be broken up when the URL wraps to another line)

**Comment by rohithbalaji123** [comment]
@Coteh , I guess we can go with `word-break: break-all`, as readability for the long links are not our primary concern. Moreover, the links are still clickable for the user navigate to the page.
For reference: https://jsfiddle.net/6mn0L35r/2/
