### ISSUE TITLE
[Feature] Documentation for each backend package

### ISSUE THREAD

**Issue by arberiii** [short-d/short#736]
**What is the problem?**
There are a lot of golang packages and sometimes I'm not sure what is the role of that specific package.

**Your solution**
For each package, we have a doc.go file that has only comments explaining the function of that package.

**Comment by byliuyang** [comment]
@arberiii I am sorry for not having enough documentation.

**Comment by arberiii** [comment]
This can be helpful https://github.com/short-d/short/blob/master/doc/clean-architecture/short-backend.jpg .
It would be nice to add [example](https://blog.golang.org/examples)

**Comment by byliuyang** [comment]
@arberiii Yes! We should add examples. We have examples in the kgs: https://github.com/short-d/kgs/blob/master/app/usecase/keys/producer_test.go

**Comment by byliuyang** [comment]
Instead of adding documentation to all packages, let's draw core architecture diagrams to help developer clear their confusions.
