### ISSUE TITLE
[BUG] After submitting a short link, cursor on long link and alias text fields moves to end of input after typing

### ISSUE THREAD

**Issue by Coteh** [short-d/short#745]
**Describe the bug**
If you open the homepage and enter a new short link, then you type one character in the middle (or beginning) of either long link or alias text fields, then the cursor will move to the end of the text field automatically.

**To Reproduce**
1. Create a short link using long link (and optionally, custom alias) of your choice
2. After it's successfully added, type anywhere before the end of the text field for either long link or alias text fields, cursor will move to the end

**Expected behavior**
Cursor should stay in place when typing, even after a short link is added.

**Screenshots**
![result](https://user-images.githubusercontent.com/3276350/81230338-4b1def80-8fbf-11ea-99bf-902ed116c8a7.gif)

**Additional context**
May have to do with the recent update to toggled feature components.

**Comment by byliuyang** [comment]
Not reproducible anymore.
