### ISSUE TITLE
[Refactor] Add foreign keys for `user` referenced tables.  

### ISSUE THREAD

**Issue by alldroll** [short-d/short#755]
**What is frustrating you?**
There are a lot of DB tables that hold the `user_id` reference which leads to data integrity violation, as anytime a `user` record can be deleted or modified.

**Your solution**
After the migration process (primary key user_email -> user_id) for `user` table to be completed, it requires adding foreign key constraints in referenced tables.

**Comment by byliuyang** [comment]
Done.
