### ISSUE TITLE
[Feature] Disable reCaptcha in Dev Environment

### ISSUE THREAD

**Issue by oatovar** [short-d/short#790]
**What is the problem?**
Testing any authenticated content in the dev environment require updating recaptcha to always return true. When testing in a dev environment recaptcha, should automatically be disabled so that contributors do not modify this part of the code during local testing.

**Your solution**
Enable/Disable features depending on the environment of the application.

**Comment by arberiii** [comment]
I second this. There are also other parts that I think needed to be modified for Dev Environment.

Do you have any solution to this in mind? I was thinking to create a Mode env variable which in case of Dev disables reCaptcha and other parts.

**Comment by byliuyang** [comment]
Please check this out: https://github.com/short-d/short/blob/master/backend/dep/provider/feature.go

**Comment by Coteh** [comment]
I think this is a good idea as well! I also find myself having to comment out reCaptcha when testing, often enough that I even have a special `git stash` entry that I apply which will automatically comment out that section. 😛 

So should we have a feature for `recaptcha`, and have this always enabled in dynamic decision maker but for the static decision maker it can be hardcoded to return false? I'd also be interested in taking this on!

**Comment by byliuyang** [comment]
@Coteh This is a good idea. I recommend just injecting a fake recaptcha service for local development. It doesn't make sense logically for dynamic feature decision maker to have hard coded value.
