### ISSUE TITLE
[Refactor] Remove business logic from gqlapi resolver

### ISSUE THREAD

**Issue by oatovar** [short-d/short#840]
**What is frustrating you?**
The gqlapi resolver uses a singular url input with all fields as optional. Since the create and update functions differ in optional field requirements, the resolver has to format the inputs so that it fits their expected inputs. Thus business logic exists within the resolver which should exist within each use case. 

**Your solution**
Update Creator and Updater to do this business logic instead of the gqlapi resolver.

**Comment by Coteh** [comment]
I'm interested in taking this once #798 goes in.

**Comment by byliuyang** [comment]
@Coteh Sounds good!

**Comment by byliuyang** [comment]
```go
type Feedback struct {
	AppID          string
	FeedbackID     string
	CustomerRating int
	Comment        *string
	CustomerEmail  *string
	ReceivedAt     time.Time
}

func (f Feedback) GetComment(defaultVal string) string {
	if f.Comment == nil {
		return defaultVal
	}
	return *f.Comment
}

func (f Feedback) GetCustomerEmail(defaultVal string) string {
	if f.CustomerEmail == nil {
		return defaultVal
	}
	return *f.CustomerEmail
}

type FeedbackInput struct {
	AppID          *string
	FeedbackID     *string
	CustomerRating *int
	Comment        *string
	CustomerEmail  *string
	ReceivedAt     *time.Time
}

func (f FeedbackInput) GetAppID() string {
	if f.AppID == nil {
		return ""
	}
	return *f.AppID
}

func (f FeedbackInput) GetFeedbackID() string {
	if f.FeedbackID == nil {
		return ""
	}
	return *f.FeedbackID
}

func (f FeedbackInput) GetCustomerRating() int {
	if f.CustomerRating == nil {
		return 0
	}
	return *f.CustomerRating
}

func (f FeedbackInput) GetReceivedAt() time.Time {
	if f.ReceivedAt == nil {
		return time.Time{}
	}
	return *f.ReceivedAt
}

```
This is the currently what I did to solve this problem! Hope this helps!

**Comment by arberiii** [comment]
@byliuyang I think this issue is about ShortLinkInput 
![image](https://user-images.githubusercontent.com/8199285/86754870-80879d80-c041-11ea-8919-bfd90ae270d0.png)

**Comment by byliuyang** [comment]
@arberiii Yes. The example is for feedback widget. Those definitions should be moved into entity package.
