### ISSUE TITLE
[Refactor] Rename URL into ShortLink in client side components

### ISSUE THREAD

**Issue by rohithbalaji123** [short-d/short#863]
**What is frustrating you?**
Currently, in all the server side packages `URL` has been renamed to `ShortLink`, but there are few packages in client side which aren't renamed. Also, in some places, `longLink` is named as `originalURL`.

**Your solution**
Rename `URL` into `shortLink` and `originalURL` into `longLink` in all of the client side components.

**Comment by bhautikbharadava** [comment]
Is this still open.? If yes , can i work on this?

**Comment by byliuyang** [comment]
@bhautikbharadava Yes, please!
