### ISSUE TITLE
[Refactor] Update user short link relation in Usecase

### ISSUE THREAD

**Issue by arberiii** [short-d/short#922]
**What is frustrating you?**
When updating the alias of a short link, the relation of user short link is updated only because they are joint in postgres database but it is not updated in updater usecase
https://github.com/short-d/short/blob/b945aac5192b0f4bb674fd6dfdbdb7d7b1f05fd3/backend/app/usecase/shortlink/updater.go#L80-L81 

**Your solution**
Update user short link relation in Usecase

**Comment by byliuyang** [comment]
Huh, good question. Not sure whether we have to manually do this.

**Comment by arberiii** [comment]
A more detailed dissucion in [issue #958](https://github.com/short-d/short/issues/958).
