### ISSUE TITLE
[Feature] Add Incident and Progress repos

### ISSUE THREAD

**Issue by Tlac** [short-d/short#971]
**What is the problem?**
We need to implement Incident and Progress repositories.
![image](https://user-images.githubusercontent.com/17193168/88119183-a9ee1080-cb8d-11ea-8dec-f0dbb1ac6dfe.png)

**Your solution**
I will add the implementation for the Incident and Progress data model based on view status diagram.

**Comment by byliuyang** [comment]
Closing for now due to priority shift.
